### PR TITLE
Create the first CI job for building PDF

### PR DESCRIPTION
**Pull request by tai271828**
Issue: #5

This pull request is tested by this CI run https://github.com/tai271828/mmnote/actions/runs/3341587043

### CODE REVIEW

**Comment by tai271828** [comment]
Ah, code base house cleaning is needed. Let me rebase for diverting commits.

**Comment by yungyuc** [comment]
It's great!  I would like to merge immediately.  But it seems the CI will be of greater use if the generated PDF files are made as downloadable artifacts.  Do you want to do it alone with this PR, or use a separate one?  If it's the latter I'd merge it right away.

**Review by yungyuc — APPROVED** [review]

**Comment by tai271828** [comment]
I am keen to use a separate one, which will be small-and-steady working pattern for me. Another positive side is anyone who is interested in the same issue could continue working on it on top of the merged PR easier.

**Comment by tai271828** [comment]
If anyone (@EN-Chou ) is interested in the following steps of "downloadable artifacts", you may refer to this page to see how to do it https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts (I did not do it before with Github, so I need to follow the same instruction as well :) ).

**Comment by tai271828** [comment]
If anyone (@EN-Chou ?) is interested in the following steps of "downloadable artifacts", you may refer to this page to see how to do it https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts (I did not do it before with Github, so I need to follow the same instruction as well :) ).

**Pull request merged**
